# Use the golang base image with a specific Go version
FROM golang:1.17 as builder

# Set the working directory to /app
WORKDIR /go/src/apexdrive

# Copy the binary file from the host into the container's working directory
COPY apexdrive-server .

# Set the final base image for the runtime container
FROM golang:1.17

# Set the working directory to /app
WORKDIR /app

# Copy the binary from the previous builder stage into the final container
COPY --from=builder /go/src/apexdrive/apexdrive-server .

# Expose the port on which your Go server listens (replace 8080 with the actual port).
EXPOSE 10001

# Command to run your Go server when the container starts.
CMD ["./apexdrive-server"]


