// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: proto/gateway/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for the start operation
type ApexDriveStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApexDriveStartRequest) Reset() {
	*x = ApexDriveStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApexDriveStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApexDriveStartRequest) ProtoMessage() {}

func (x *ApexDriveStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApexDriveStartRequest.ProtoReflect.Descriptor instead.
func (*ApexDriveStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

// Request message for the start operation
type MaleniaStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MaleniaStartRequest) Reset() {
	*x = MaleniaStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaleniaStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaleniaStartRequest) ProtoMessage() {}

func (x *MaleniaStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaleniaStartRequest.ProtoReflect.Descriptor instead.
func (*MaleniaStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

// Request message for the start operation
type TimeSquaredStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TimeSquaredStartRequest) Reset() {
	*x = TimeSquaredStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSquaredStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSquaredStartRequest) ProtoMessage() {}

func (x *TimeSquaredStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSquaredStartRequest.ProtoReflect.Descriptor instead.
func (*TimeSquaredStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

// Request message for the start operation
type IndriyasStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IndriyasStartRequest) Reset() {
	*x = IndriyasStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndriyasStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndriyasStartRequest) ProtoMessage() {}

func (x *IndriyasStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndriyasStartRequest.ProtoReflect.Descriptor instead.
func (*IndriyasStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

// Request message for the start operation
type NeithStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NeithStartRequest) Reset() {
	*x = NeithStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeithStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeithStartRequest) ProtoMessage() {}

func (x *NeithStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeithStartRequest.ProtoReflect.Descriptor instead.
func (*NeithStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

// Request message for the status operation
type ApexDriveStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApexDriveStatusRequest) Reset() {
	*x = ApexDriveStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApexDriveStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApexDriveStatusRequest) ProtoMessage() {}

func (x *ApexDriveStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApexDriveStatusRequest.ProtoReflect.Descriptor instead.
func (*ApexDriveStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

// Request message for the status operation
type MaleniaStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MaleniaStatusRequest) Reset() {
	*x = MaleniaStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaleniaStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaleniaStatusRequest) ProtoMessage() {}

func (x *MaleniaStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaleniaStatusRequest.ProtoReflect.Descriptor instead.
func (*MaleniaStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{6}
}

// Request message for the status operation
type TimeSquaredStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TimeSquaredStatusRequest) Reset() {
	*x = TimeSquaredStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSquaredStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSquaredStatusRequest) ProtoMessage() {}

func (x *TimeSquaredStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSquaredStatusRequest.ProtoReflect.Descriptor instead.
func (*TimeSquaredStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{7}
}

// Request message for the status operation
type IndriyasStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IndriyasStatusRequest) Reset() {
	*x = IndriyasStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndriyasStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndriyasStatusRequest) ProtoMessage() {}

func (x *IndriyasStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndriyasStatusRequest.ProtoReflect.Descriptor instead.
func (*IndriyasStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{8}
}

// Request message for the status operation
type NeithStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NeithStatusRequest) Reset() {
	*x = NeithStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeithStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeithStatusRequest) ProtoMessage() {}

func (x *NeithStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeithStatusRequest.ProtoReflect.Descriptor instead.
func (*NeithStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{9}
}

// Response message for the Gateway service
type GatewayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GatewayResponse) Reset() {
	*x = GatewayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gateway_gateway_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayResponse) ProtoMessage() {}

func (x *GatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayResponse.ProtoReflect.Descriptor instead.
func (*GatewayResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{10}
}

var File_proto_gateway_gateway_proto protoreflect.FileDescriptor

var file_proto_gateway_gateway_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x41, 0x70, 0x65, 0x78, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x15, 0x0a, 0x13, 0x4d, 0x61, 0x6c, 0x65, 0x6e, 0x69, 0x61, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x71,
	0x75, 0x61, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x16, 0x0a, 0x14, 0x49, 0x6e, 0x64, 0x72, 0x69, 0x79, 0x61, 0x73, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x4e, 0x65, 0x69,
	0x74, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18,
	0x0a, 0x16, 0x41, 0x70, 0x65, 0x78, 0x44, 0x72, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x4d, 0x61, 0x6c, 0x65,
	0x6e, 0x69, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x1a, 0x0a, 0x18, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15,
	0x49, 0x6e, 0x64, 0x72, 0x69, 0x79, 0x61, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x4e, 0x65, 0x69, 0x74, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x92,
	0x06, 0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4c, 0x0a, 0x0e, 0x41, 0x70, 0x65, 0x78, 0x44, 0x72, 0x69, 0x76, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x1e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x41, 0x70,
	0x65, 0x78, 0x44, 0x72, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x0c, 0x4d, 0x61, 0x6c, 0x65, 0x6e, 0x69, 0x61, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x1c, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x61, 0x6c, 0x65, 0x6e, 0x69,
	0x61, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x10, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x20, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x71, 0x75, 0x61,
	0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x49,
	0x6e, 0x64, 0x72, 0x69, 0x79, 0x61, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1d, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x49, 0x6e, 0x64, 0x72, 0x69, 0x79, 0x61, 0x73, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0a, 0x4e, 0x65, 0x69, 0x74, 0x68,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x4e, 0x65, 0x69, 0x74, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a,
	0x0f, 0x41, 0x70, 0x65, 0x78, 0x44, 0x72, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1f, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x41, 0x70, 0x65, 0x78, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a,
	0x0d, 0x4d, 0x61, 0x6c, 0x65, 0x6e, 0x69, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x61, 0x6c, 0x65, 0x6e, 0x69, 0x61,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x11, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x71, 0x75,
	0x61, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a,
	0x0e, 0x49, 0x6e, 0x64, 0x72, 0x69, 0x79, 0x61, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x49, 0x6e, 0x64, 0x72, 0x69, 0x79,
	0x61, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x4e,
	0x65, 0x69, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x4e, 0x65, 0x69, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_gateway_proto_rawDescData = file_proto_gateway_gateway_proto_rawDesc
)

func file_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gateway_gateway_proto_rawDescData)
	})
	return file_proto_gateway_gateway_proto_rawDescData
}

var file_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_gateway_gateway_proto_goTypes = []interface{}{
	(*ApexDriveStartRequest)(nil),    // 0: gateway.ApexDriveStartRequest
	(*MaleniaStartRequest)(nil),      // 1: gateway.MaleniaStartRequest
	(*TimeSquaredStartRequest)(nil),  // 2: gateway.TimeSquaredStartRequest
	(*IndriyasStartRequest)(nil),     // 3: gateway.IndriyasStartRequest
	(*NeithStartRequest)(nil),        // 4: gateway.NeithStartRequest
	(*ApexDriveStatusRequest)(nil),   // 5: gateway.ApexDriveStatusRequest
	(*MaleniaStatusRequest)(nil),     // 6: gateway.MaleniaStatusRequest
	(*TimeSquaredStatusRequest)(nil), // 7: gateway.TimeSquaredStatusRequest
	(*IndriyasStatusRequest)(nil),    // 8: gateway.IndriyasStatusRequest
	(*NeithStatusRequest)(nil),       // 9: gateway.NeithStatusRequest
	(*GatewayResponse)(nil),          // 10: gateway.GatewayResponse
}
var file_proto_gateway_gateway_proto_depIdxs = []int32{
	0,  // 0: gateway.GatewayService.ApexDriveStart:input_type -> gateway.ApexDriveStartRequest
	1,  // 1: gateway.GatewayService.MaleniaStart:input_type -> gateway.MaleniaStartRequest
	2,  // 2: gateway.GatewayService.TimeSquaredStart:input_type -> gateway.TimeSquaredStartRequest
	3,  // 3: gateway.GatewayService.IndriyasStart:input_type -> gateway.IndriyasStartRequest
	4,  // 4: gateway.GatewayService.NeithStart:input_type -> gateway.NeithStartRequest
	5,  // 5: gateway.GatewayService.ApexDriveStatus:input_type -> gateway.ApexDriveStatusRequest
	6,  // 6: gateway.GatewayService.MaleniaStatus:input_type -> gateway.MaleniaStatusRequest
	7,  // 7: gateway.GatewayService.TimeSquaredStatus:input_type -> gateway.TimeSquaredStatusRequest
	8,  // 8: gateway.GatewayService.IndriyasStatus:input_type -> gateway.IndriyasStatusRequest
	9,  // 9: gateway.GatewayService.NeithStatus:input_type -> gateway.NeithStatusRequest
	10, // 10: gateway.GatewayService.ApexDriveStart:output_type -> gateway.GatewayResponse
	10, // 11: gateway.GatewayService.MaleniaStart:output_type -> gateway.GatewayResponse
	10, // 12: gateway.GatewayService.TimeSquaredStart:output_type -> gateway.GatewayResponse
	10, // 13: gateway.GatewayService.IndriyasStart:output_type -> gateway.GatewayResponse
	10, // 14: gateway.GatewayService.NeithStart:output_type -> gateway.GatewayResponse
	10, // 15: gateway.GatewayService.ApexDriveStatus:output_type -> gateway.GatewayResponse
	10, // 16: gateway.GatewayService.MaleniaStatus:output_type -> gateway.GatewayResponse
	10, // 17: gateway.GatewayService.TimeSquaredStatus:output_type -> gateway.GatewayResponse
	10, // 18: gateway.GatewayService.IndriyasStatus:output_type -> gateway.GatewayResponse
	10, // 19: gateway.GatewayService.NeithStatus:output_type -> gateway.GatewayResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_gateway_proto_init() }
func file_proto_gateway_gateway_proto_init() {
	if File_proto_gateway_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gateway_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApexDriveStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaleniaStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSquaredStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndriyasStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NeithStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApexDriveStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaleniaStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSquaredStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndriyasStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NeithStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gateway_gateway_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gateway_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_gateway_proto = out.File
	file_proto_gateway_gateway_proto_rawDesc = nil
	file_proto_gateway_gateway_proto_goTypes = nil
	file_proto_gateway_gateway_proto_depIdxs = nil
}
