// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: proto/apexdrive/apexdrive.proto

package apexdrive

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ApexDriveService_HealthCheck_FullMethodName = "/apexdrive.ApexDriveService/HealthCheck"
)

// ApexDriveServiceClient is the client API for ApexDriveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApexDriveServiceClient interface {
	// Healthcheck operation
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type apexDriveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApexDriveServiceClient(cc grpc.ClientConnInterface) ApexDriveServiceClient {
	return &apexDriveServiceClient{cc}
}

func (c *apexDriveServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ApexDriveService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApexDriveServiceServer is the server API for ApexDriveService service.
// All implementations must embed UnimplementedApexDriveServiceServer
// for forward compatibility
type ApexDriveServiceServer interface {
	// Healthcheck operation
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedApexDriveServiceServer()
}

// UnimplementedApexDriveServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApexDriveServiceServer struct {
}

func (UnimplementedApexDriveServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedApexDriveServiceServer) mustEmbedUnimplementedApexDriveServiceServer() {}

// UnsafeApexDriveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApexDriveServiceServer will
// result in compilation errors.
type UnsafeApexDriveServiceServer interface {
	mustEmbedUnimplementedApexDriveServiceServer()
}

func RegisterApexDriveServiceServer(s grpc.ServiceRegistrar, srv ApexDriveServiceServer) {
	s.RegisterService(&ApexDriveService_ServiceDesc, srv)
}

func _ApexDriveService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApexDriveServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApexDriveService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApexDriveServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApexDriveService_ServiceDesc is the grpc.ServiceDesc for ApexDriveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApexDriveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apexdrive.ApexDriveService",
	HandlerType: (*ApexDriveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ApexDriveService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/apexdrive/apexdrive.proto",
}
