// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: proto/malenia/malenia.proto

package malenia

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MaleniaService_HealthCheck_FullMethodName = "/malenia.MaleniaService/HealthCheck"
)

// MaleniaServiceClient is the client API for MaleniaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaleniaServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type maleniaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaleniaServiceClient(cc grpc.ClientConnInterface) MaleniaServiceClient {
	return &maleniaServiceClient{cc}
}

func (c *maleniaServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MaleniaService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaleniaServiceServer is the server API for MaleniaService service.
// All implementations must embed UnimplementedMaleniaServiceServer
// for forward compatibility
type MaleniaServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedMaleniaServiceServer()
}

// UnimplementedMaleniaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMaleniaServiceServer struct {
}

func (UnimplementedMaleniaServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMaleniaServiceServer) mustEmbedUnimplementedMaleniaServiceServer() {}

// UnsafeMaleniaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaleniaServiceServer will
// result in compilation errors.
type UnsafeMaleniaServiceServer interface {
	mustEmbedUnimplementedMaleniaServiceServer()
}

func RegisterMaleniaServiceServer(s grpc.ServiceRegistrar, srv MaleniaServiceServer) {
	s.RegisterService(&MaleniaService_ServiceDesc, srv)
}

func _MaleniaService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaleniaServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaleniaService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaleniaServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MaleniaService_ServiceDesc is the grpc.ServiceDesc for MaleniaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaleniaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "malenia.MaleniaService",
	HandlerType: (*MaleniaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _MaleniaService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/malenia/malenia.proto",
}
